const std = @import("std");
const Generator = @import("../Generator.zig");
const Node = @import("../../input/element/Node.zig");

pub const Error = error{};
const GeneratorError = Generator.Error;

pub const r = Generator.Rule.def;
pub const mr = Generator.MetaRule.def;

// TODO: all these three big types should be overworked / merged
pub const metarules = [_]Generator.MetaRule{
    mr(.UnorderedItemListOpen, "<ul>"),
    mr(.UnorderedItemListClose, "</ul>"),
    mr(.OrderedItemListOpen, "<ol>"),
    mr(.OrderedItemListClose, "</ol>"),
    mr(.HeadOpen, "<head>"),
    mr(.HeadClose, "</head>"),
    mr(.BodyOpen, "<body>"),
    mr(.BodyClose, "</body>"),
};

pub const rules = [_]Generator.Rule{
    r(.BeginMeta, "<!DOCTYPE html><html>"),
    r(.EndMeta, "</body></html>\n\n <!-- generated by ct2html -->"),

    r(.AttributeBeginMeta, "<head>"),
    r(.AttributeEndMeta, "</head><body>"),
    r(.AttributeStyle, .{ "<link rel=\"stylesheet\" href=\"", "\">" }),
    r(.AttributeHeader, .{ "<title>", "</title>" }),

    r(.Heading1, .{ "<h1>", "</h1>" }),
    r(.Heading2, .{ "<h2>", "</h2>" }),
    r(.Heading3, .{ "<h3>", "</h3>" }),
    r(.Heading4, .{ "<h4>", "</h4>" }),
    r(.Heading5, .{ "<h5>", "</h5>" }),
    r(.Heading6, .{ "<h6>", "</h6>" }),

    r(.Paragraph, .{ "<p>", "</p>" }),

    r(.UnorderedListBeginMeta, "<ul>"),
    r(.UnorderedListEndMeta, "</ul>"),

    r(.DashItem, .{ "<li>", "</li>" }),

    r(.OrderedListBeginMeta, "<ol>"),
    r(.OrderedListEndMeta, "</ol>"),

    r(.NumDotItemLabel, .{ "<li value=\"", "\">" }),
    r(.NumDotItemText, .{ "", "</li>" }),

    r(.NumParenItemLabel, .{ "<li value=\"", "\">" }),
    r(.NumParenItemText, .{ "", "</li>" }),

    // since we have two fields, link and text
    r(.CommandLink, &command_link),
    r(.CommandImage, &command_img),

    r(.InlineCode, .{ "<code>", "</code>" }),

    r(.Bold, .{ "<strong>", "</strong>" }),
    r(.Italic, .{ "<em>", "</em>" }),
    r(.BoldItalic, .{ "<strong><em>", "</em></strong>" }),

    r(.Strikethrough, .{ "<del>", "</del>" }),
    r(.StrikethroughBold, .{ "<del><strong>", "</strong></del>" }),
    r(.StrikethroughItalic, .{ "<del><em>", "</em></del>" }),
    r(.StrikethroughBoldItalic, .{ "<del><strong><em>", "</em></strong></del>" }),
};

pub const l1_margins = std.EnumMap(Node.KindLevel1, struct { usize, usize }).init(.{
    .CommandLink = .{ "@link(".len, ")".len },
    .CommandImage = .{ "@image(".len, ")".len },

    .InlineCode = .{ 1, 1 },

    .Bold = .{ 1, 1 },
    .Italic = .{ 2, 2 },
    .BoldItalic = .{ 3, 3 },

    .Strikethrough = .{ 1, 1 },
    .StrikethroughBold = .{ 2, 2 },
    .StrikethroughItalic = .{ 3, 3 },
    .StrikethroughBoldItalic = .{ 4, 4 },
});

pub fn rule_by_kind(k: Node.Kind) !Generator.Rule {
    for (rules) |rule| {
        if (rule.kind.eq(k)) return rule;
    }
    return error.NoRuleForKind;
}

// TODO check again
fn command_link(g: *Generator) GeneratorError![]const u8 {
    // CommandLink contains of text with some , in it, try to find it
    const node = g.peek_node() orelse return GeneratorError.L0NodeNotFound;
    const text = g.textin[node.textstart..node.textend];
    if (std.mem.find(u8, text, &.{','})) |comma_index| {
        const link = text[0..comma_index];
        const link_text = text[comma_index + 1 ..];
        return std.fmt.allocPrint(
            g.arenalloc,
            "<a href=\"{s}\">{s}</a>",
            .{ link, link_text },
        ) catch return GeneratorError.OOM;
    } else {
        // only link
        return g.textin[node.textstart..node.textend];
    }
}

fn command_img(g: *Generator) GeneratorError![]const u8 {
    _ = g;
    return "image TODO"; // TODO
}
