const std = @import("std");
const Generator = @import("../Generator.zig");
const Node = @import("../../input/element/Node.zig");

pub const Error = error{};
const GeneratorError = Generator.Error;

pub const r = Generator.Rule.def;
pub const mr = Generator.MetaRule.def;

pub const metarules = [_]Generator.MetaRule{
    mr(.UnorderedItemListOpen, "<ul>"),
    mr(.UnorderedItemListClose, "</ul>"),
    mr(.OrderedItemListOpen, "<ol>"),
    mr(.OrderedItemListClose, "</ol>"),
    mr(.HeadOpen, "<head>"),
    mr(.HeadClose, "</head>"),
    mr(.BodyOpen, "<body>"),
    mr(.BodyClose, "</body>"),
};

pub const rules = [_]Generator.Rule{
    r(.l0(.BeginMeta), .xprepost("<!DOCTYPE html><html>", "")),
    r(.l0(.EndMeta), .xprepost("</body></html>\n\n <!-- generated by ct2html -->", "")),

    r(.l0(.AttributeBeginMeta), .xprepost("<head>", "")),
    r(.l0(.AttributeEndMeta), .xprepost("</head><body>", "")),
    r(.l0(.AttributeStyle), .xprepost("<link rel=\"stylesheet\" href=\"", "\">")),
    r(.l0(.AttributeHeader), .xprepost("<title>", "</title>")),

    r(.l0(.Heading1), .xprepost("<h1>", "</h1>")),
    r(.l0(.Heading2), .xprepost("<h2>", "</h2>")),
    r(.l0(.Heading3), .xprepost("<h3>", "</h3>")),
    r(.l0(.Heading4), .xprepost("<h4>", "</h4>")),
    r(.l0(.Heading5), .xprepost("<h5>", "</h5>")),
    r(.l0(.Heading6), .xprepost("<h6>", "</h6>")),

    r(.l0(.Paragraph), .xprepost("<p>", "</p>")),

    r(.l0(.UnorderedListBeginMeta), .xprepost("<ul>", "")),
    r(.l0(.UnorderedListEndMeta), .xprepost("</ul>", "")),

    r(.l0(.DashItem), .xprepost("<li>", "</li>")),

    r(.l0(.OrderedListBeginMeta), .xprepost("<ol>", "")),
    r(.l0(.OrderedListEndMeta), .xprepost("</ol>", "")),

    r(.l0(.NumDotItemLabel), .xprepost("<li value=\"", "\">")),
    r(.l0(.NumDotItemText), .xprepost("", "</li>")),

    r(.l0(.NumParenItemLabel), .xprepost("<li value=\"", "\">")),
    r(.l0(.NumParenItemText), .xprepost("", "</li>")),

    r(.l0(.AlphDotItemLabel), .xprepost("<li value=\"", "\">")),
    r(.l0(.AlphDotItemText), .xprepost("", "</li>")),

    r(.l0(.AlphParenItemLabel), .xprepost("<li value=\"", "\">")),
    r(.l0(.AlphParenItemText), .xprepost("", "</li>")),

    // since we have two fields, link and text
    r(.l1(.CommandLink), .xreplace(&command_link)),
    r(.l1(.CommandImage), .xreplace(&command_img)),

    r(.l1(.InlineCode), .xprepost("<code>", "</code>")),

    r(.l1(.Bold), .xprepost("<strong>", "</strong>")),
    r(.l1(.Italic), .xprepost("<em>", "</em>")),
    r(.l1(.BoldItalic), .xprepost("<strong><em>", "</em></strong>")),

    r(.l1(.Strikethrough), .xprepost("<del>", "</del>")),
    r(.l1(.StrikethroughBold), .xprepost("<del><strong>", "</strong></del>")),
    r(.l1(.StrikethroughItalic), .xprepost("<del><em>", "</em></del>")),
    r(.l1(.StrikethroughBoldItalic), .xprepost("<del><strong><em>", "</em></strong></del>")),
};

pub const l1_margins = std.EnumMap(Node.KindLevel1, struct { usize, usize }).init(.{
    .CommandLink = .{ "@link(".len, ")".len },
    .CommandImage = .{ "@image(".len, ")".len },

    .InlineCode = .{ 1, 1 },

    .Bold = .{ 1, 1 },
    .Italic = .{ 2, 2 },
    .BoldItalic = .{ 3, 3 },

    .Strikethrough = .{ 1, 1 },
    .StrikethroughBold = .{ 2, 2 },
    .StrikethroughItalic = .{ 3, 3 },
    .StrikethroughBoldItalic = .{ 4, 4 },
});

pub fn rule_by_kind(k: Node.Kind) !Generator.Rule {
    for (rules) |rule| {
        if (rule.kind.eq(k)) return rule;
    }
    return error.NoRuleForKind;
}

fn command_link(g: *Generator) GeneratorError![]const u8 {
    // CommandLink contains of text with some , in it, try to find it
    const node = g.peek_node() orelse return GeneratorError.L0NodeNotFound;
    const text = g.textin[node.textstart..node.textend];
    if (std.mem.find(u8, text, &.{','})) |comma_index| {
        const link = text[0..comma_index];
        const link_text = text[comma_index + 1 ..];
        return std.fmt.allocPrint(
            g.arenalloc,
            "<a href=\"{s}\">{s}</a>",
            .{ link, link_text },
        ) catch return GeneratorError.OOM;
    } else {
        // only link
        return g.textin[node.textstart..node.textend];
    }
}

fn command_img(g: *Generator) GeneratorError![]const u8 {
    _ = g;
    return "image TODO"; // TODO
}
