const std = @import("std");
const Generator = @import("Generator.zig");
const Node = @import("../element/Node.zig");
const Rule = @import("../element/Rule.zig");
const cc_rules = @import("special/cc_rules.zig");
const hack = @import("../hack.zig");
const crash = @import("../ErrorReporter.zig").crash;

pub const datatable = hack.StructByteMap(.{
    .{
        .{Node.L0Kind.begin},
        Rule.GenDef.def("<!DOCTYPE html><html><head><meta charset=\"UTF-8\">", "", .all_esc),
    },
    .{
        .{Node.L0Kind.end},
        Rule.GenDef.def("</body></html>\n\n <!-- generated by ct2html -->\n", "", .all_esc),
    },
    .{
        .{Node.L0Kind.head_anchor},
        Rule.GenDef.def(&head_sec, "", .all_esc),
    },
    .{
        .{Node.L0Kind.heading1},
        Rule.GenDef.def("<h1>", "</h1>", .all_esc),
    },
    .{
        .{Node.L0Kind.heading2},
        Rule.GenDef.def(&generic_pre_anchored_heading, "</a></h2>", .all_esc),
    },
    .{
        .{Node.L0Kind.heading3},
        Rule.GenDef.def(&generic_pre_anchored_heading, "</a></h3>", .all_esc),
    },
    .{
        .{Node.L0Kind.heading4},
        Rule.GenDef.def(&generic_pre_anchored_heading, "</a></h4>", .all_esc),
    },
    .{
        .{Node.L0Kind.heading5},
        Rule.GenDef.def(&generic_pre_anchored_heading, "</a></h5>", .all_esc),
    },
    .{
        .{Node.L0Kind.heading6},
        Rule.GenDef.def(&generic_pre_anchored_heading, "</a></h6>", .all_esc),
    },

    .{
        .{Node.L0Kind.quote_block},
        Rule.GenDef.def("<blockquote>", "</blockquote>", .all_esc),
    },
    .{
        .{Node.L0Kind.bold_quote_block},
        Rule.GenDef.def("<blockquote><strong>", "</strong></blockquote>", .all_esc),
    },
    .{
        .{Node.L0Kind.italic_quote_block},
        Rule.GenDef.def("<blockquote><em>", "</em></blockquote>", .all_esc),
    },
    .{
        .{Node.L0Kind.bold_italic_quote_block},
        Rule.GenDef.def("<blockquote><em><strong>", "</strong></em></blockquote>", .all_esc),
    },

    .{
        .{Node.L0Kind.paragraph},
        Rule.GenDef.def("<p>", "</p>", .all_esc),
    },
    .{
        .{Node.L0Kind.nonparagraph},
        Rule.GenDef.def("", "", .all_esc),
    },

    .{
        .{Node.L0Kind.code_block_header},
        Rule.GenDef.def("<div class=\"code-header\">", "</div>", .all_esc),
    },
    .{
        .{Node.L0Kind.code_block_meta},
        Rule.GenDef.def("<pre><code class=\"language-", "\">", .all_esc),
    },
    .{
        .{Node.L0Kind.code_block},
        Rule.GenDef.def("", "</code></pre>", .html_esc), // to not need to write \\ for single \
    },

    .{
        .{Node.L0Kind.unordered_list_begin},
        Rule.GenDef.def("<ul>", "", .all_esc),
    },
    .{
        .{Node.L0Kind.unordered_list_end},
        Rule.GenDef.def("</ul>", "", .all_esc),
    },

    .{
        .{Node.L0Kind.dash_item},
        Rule.GenDef.def("<li>", "</li>", .all_esc),
    },

    .{
        .{Node.L0Kind.ordered_list_begin},
        Rule.GenDef.def("<ol>", "", .all_esc),
    },
    .{
        .{Node.L0Kind.ordered_list_end},
        Rule.GenDef.def("</ol>", "", .all_esc),
    },

    .{
        .{Node.L0Kind.num_dot_item_label},
        Rule.GenDef.def("<li value=\"", "\">", .all_esc),
    },
    .{
        .{Node.L0Kind.num_dot_item_text},
        Rule.GenDef.def("", "</li>", .all_esc),
    },

    .{
        .{Node.L0Kind.num_paren_item_label},
        Rule.GenDef.def("<li value=\"", "\">", .all_esc),
    },
    .{
        .{Node.L0Kind.num_paren_item_text},
        Rule.GenDef.def("", "</li>", .all_esc),
    },

    .{
        .{Node.L0Kind.blk_cmd_img_0src},
        Rule.GenDef.def("<figure><img src=\"", "\" ", .direct),
    },
    .{
        .{Node.L0Kind.blk_cmd_img_1size},
        Rule.GenDef.def("style=\"width:", "; height: auto;\" alt=\"\" />", .direct),
    },
    .{
        .{Node.L0Kind.blk_cmd_img_2caption_l1c},
        Rule.GenDef.def("<figcaption>", "</figcaption></figure>", .all_esc),
    },

    .{
        .{Node.L0Kind.blk_cmd_script_link},
        Rule.GenDef.def("<script src=\"", "\"></script>", .direct),
    },
    .{
        .{Node.L0Kind.blk_cmd_style_link},
        Rule.GenDef.def("<link rel=\"stylesheet\" href=\"", "\">", .direct),
    },
    .{
        .{Node.L0Kind.blk_cmd_stylecode_code},
        Rule.GenDef.def("<style>", "</style>", .direct),
    },
    .{
        .{Node.L0Kind.blk_cmd_scriptcode_code},
        Rule.GenDef.def("<script>", "</script>", .direct),
    },
    .{
        .{Node.L0Kind.blk_cmd_ar_text_l1c},
        Rule.GenDef.def("<p dir=\"rtl\" lang=\"ar\">", "</p>", .direct),
    },
    .{
        .{Node.L0Kind.blk_cmd_header_text_l1c},
        Rule.GenDef.def("<header>", "</header>", .all_esc),
    },
    .{
        .{Node.L0Kind.blk_cmd_footer_text_l1c},
        Rule.GenDef.def("<footer>", "</footer>", .all_esc),
    },
    .{
        .{Node.L0Kind.blk_cmd_details_0summary_l1c},
        Rule.GenDef.def("<details><summary>", "</summary>", .all_esc),
    },
    .{
        .{Node.L0Kind.blk_cmd_details_1text_l1c},
        Rule.GenDef.def("", "</details>", .all_esc),
    },
    .{
        .{Node.L0Kind.blk_cmd_info_0summary_l1c},
        Rule.GenDef.def("<aside class=\"info\" data-title=\"", "\">", .all_esc),
    },
    .{
        .{Node.L0Kind.blk_cmd_info_1text_l1c},
        Rule.GenDef.def("", "</aside>", .all_esc),
    },
    .{
        .{Node.L0Kind.blk_custom_cmd_arg},
        Rule.GenDef.def(&cc_rules.custom_pre, &cc_rules.custom_post, .all_esc),
    },

    // L1
    .{
        .{Node.L1Kind.inline_code},
        Rule.GenDef.def("<code>", "</code>", .all_esc), // for escaping \)
    },

    .{
        .{Node.L1Kind.bold},
        Rule.GenDef.def("<strong>", "</strong>", .all_esc),
    },
    .{
        .{Node.L1Kind.italic},
        Rule.GenDef.def("<em>", "</em>", .all_esc),
    },
    .{
        .{Node.L1Kind.bold_italic},
        Rule.GenDef.def("<strong><em>", "</em></strong>", .all_esc),
    },

    .{
        .{Node.L1Kind.strikethrough},
        Rule.GenDef.def("<del>", "</del>", .all_esc),
    },
    .{
        .{Node.L1Kind.strikethrough_bold},
        Rule.GenDef.def("<del><strong>", "</strong></del>", .all_esc),
    },
    .{
        .{Node.L1Kind.strikethrough_italic},
        Rule.GenDef.def("<del><em>", "</em></del>", .all_esc),
    },
    .{
        .{Node.L1Kind.strikethrough_bold_italic},
        Rule.GenDef.def("<del><strong><em>", "</em></strong></del>", .all_esc),
    },
    .{
        .{Node.L1Kind.sidenote},
        Rule.GenDef.def(&pre_sidenote, "<span style=\"font-size: 0;\">)</span></span>", .all_esc),
    },
    .{
        .{Node.L1Kind.inl_cmd_raw_text},
        Rule.GenDef.def("", "", .bs_esc), // only to escape \\, but < > and their brothers not
    },
    .{
        .{Node.L1Kind.inl_cmd_link_0url},
        Rule.GenDef.def("<a href=\"", "\">", .direct),
    },
    .{
        .{Node.L1Kind.inl_cmd_link_1displayname_l1c},
        Rule.GenDef.def("", "</a>", .all_esc),
    },
    .{
        .{Node.L1Kind.inl_cmd_ar_text_l1c},
        Rule.GenDef.def("<span dir=\"rtl\" lang=\"ar\">", "</span>", .all_esc),
    },
    .{
        .{Node.L1Kind.inl_cmd_div_0class},
        Rule.GenDef.def("<div class=\"", "\">", .direct),
    },
    .{
        .{Node.L1Kind.inl_cmd_div_1text_l1c},
        Rule.GenDef.def("", "</div>", .all_esc),
    },
    .{
        .{Node.L1Kind.inl_cmd_span_0class},
        Rule.GenDef.def("<span class=\"", "\">", .direct),
    },
    .{
        .{Node.L1Kind.inl_cmd_span_1text_l1c},
        Rule.GenDef.def("", "</span>", .all_esc),
    },
    .{
        .{Node.L1Kind.inl_cmd_color_0color},
        Rule.GenDef.def("<span style=\"color: ", "\">", .direct),
    },
    .{
        .{Node.L1Kind.inl_cmd_color_1text_l1c},
        Rule.GenDef.def("", "</span>", .all_esc),
    },
    .{
        .{Node.L1Kind.inl_cmd_fs_0size},
        Rule.GenDef.def("<span style=\"font-size: ", "\">", .direct),
    },
    .{
        .{Node.L1Kind.inl_cmd_fs_1text_l1c},
        Rule.GenDef.def("", "</span>", .all_esc),
    },
    .{
        .{Node.L1Kind.inl_custom_cmd_arg},
        Rule.GenDef.def(&cc_rules.custom_pre, &cc_rules.custom_post, .all_esc),
    },
}).init();

// for those attributes that get generated into the head section
fn head_sec(g: *Generator, _: *anyopaque) Generator.GenError!?@Vector(2, usize) {
    while (g.attributor.pop()) |l0node| {
        switch (l0node.kind) {
            .style => {
                g.print_direct("<link rel=\"stylesheet\" href=\"");
                g.print_direct(g.textin[l0node.span.?[0]..l0node.span.?[1]]);
                g.print_direct("\">");
            },
            .script => {
                g.print_direct("<script src=\"");
                g.print_direct(g.textin[l0node.span.?[0]..l0node.span.?[1]]);
                g.print_direct("\"></script>");
            },
            .stylecode => {
                g.print_direct("<style>");
                g.print_direct(g.textin[l0node.span.?[0]..l0node.span.?[1]]);
                g.print_direct("</style>");
            },
            .scriptcode => {
                g.print_direct("<script>");
                g.print_direct(g.textin[l0node.span.?[0]..l0node.span.?[1]]);
                g.print_direct("</script>");
            },
            .title => {
                g.print_direct("<title>");
                g.print_direct(g.textin[l0node.span.?[0]..l0node.span.?[1]]);
                g.print_direct("</title>");
            },
            else => {},
        }
    }
    g.attributor.reset_cursor();
    g.print_direct("</head>\n<body>"); // opening was already printed.
    return null; // nothing to inspect in here
}

fn pre_sidenote(g: *Generator, node: *anyopaque) Generator.GenError!?@Vector(2, usize) {
    const realnode: *Node.L0 = @ptrCast(@alignCast(node));
    const span = realnode.span;

    g.sidenote_count += 1;
    var int_to_str_buf: [32]u8 = undefined;

    const sidenote_count_str = std.fmt.bufPrint(
        &int_to_str_buf,
        "{}",
        .{g.sidenote_count},
    ) catch crash(error.OOM);

    g.print_direct("<label for=\"sn-");
    g.print_direct(sidenote_count_str);
    g.print_direct("\" class=\"margin-toggle sidenote-number\" data-sidenote-count=\"");
    g.print_direct(sidenote_count_str);
    g.print_direct("\">");
    g.print_direct("</label><input type=\"checkbox\" id=\"sn-");
    g.print_direct(sidenote_count_str);
    g.print_direct("\" class=\"margin-toggle\"><span class=\"sidenote\" data-sidenote-count=\"");
    g.print_direct(sidenote_count_str);
    g.print_direct("\"><span style=\"font-size: 0;\"> (</span>");

    return span;
}

fn generic_pre_anchored_heading(
    g: *Generator,
    node: *anyopaque,
) Generator.GenError!?@Vector(2, usize) {
    const realnode: *Node.L0 = @ptrCast(@alignCast(node));
    const span = realnode.span;

    if (span == null) crash(error.NullSpan);

    const anchorbuf: []u8 = g.alloc.alloc(u8, span.?[1] - span.?[0]) catch crash(error.OOM);
    defer g.alloc.free(anchorbuf);
    @memcpy(anchorbuf, g.textin[span.?[0]..span.?[1]]);

    for (anchorbuf) |*c| {
        if (!std.ascii.isAlphanumeric(c.*)) {
            c.* = '-';
        } else if (std.ascii.isUpper(c.*)) {
            c.* = std.ascii.toLower(c.*);
        }
    }

    switch (realnode.kind) {
        .heading2 => g.print_direct("<h2 "),
        .heading3 => g.print_direct("<h3 "),
        .heading4 => g.print_direct("<h4 "),
        .heading5 => g.print_direct("<h5 "),
        .heading6 => g.print_direct("<h6 "),
        else => unreachable,
    }

    g.print_direct("id=\"");
    g.print_direct(anchorbuf);
    g.print_direct("\"><a href=\"#");
    g.print_direct(anchorbuf);
    g.print_direct("\" class=\"heading-link\">");
    if (g.attributor.get_newest(.heading_icon)) |l0_icon_node| {
        g.print_direct("<span class=\"chain-icon\">");
        g.print_direct(g.textin[l0_icon_node.span.?[0]..l0_icon_node.span.?[1]]);
        g.print_direct("</span>");
    }

    return span;
}
