const std = @import("std");
const Generator = @import("Generator.zig");
const Node = @import("../element/Node.zig");
const Rule = @import("../element/Rule.zig");

// TODO: arabic parser
pub const rule_defs = [_]Rule.GenDef{
    .def(Node.L0Kind.begin, "<!DOCTYPE html><html>"),
    .def(Node.L0Kind.end, "</body></html>\n\n <!-- generated by ct2html -->\n"),

    .def(Node.L0Kind.attribute_begin, "<head>"),
    .def(Node.L0Kind.attribute_end, "</head><body>"),
    .def(Node.L0Kind.style, .{ "<link rel=\"stylesheet\" href=\"", "\">" }),
    .def(Node.L0Kind.script, .{ "<script src=\"", "\"></script>" }),
    .def(Node.L0Kind.header, .{ "<title>", "</title>" }),
    .def(Node.L0Kind.raw, .{ "", "" }), // just passed through

    .def(Node.L0Kind.heading1, .{ "<h1>", "</h1>" }),
    .def(Node.L0Kind.heading2, .{ "<h2>", "</h2>" }),
    .def(Node.L0Kind.heading3, .{ "<h3>", "</h3>" }),
    .def(Node.L0Kind.heading4, .{ "<h4>", "</h4>" }),
    .def(Node.L0Kind.heading5, .{ "<h5>", "</h5>" }),
    .def(Node.L0Kind.heading6, .{ "<h6>", "</h6>" }),

    .def(Node.L0Kind.quote_block, .{ "<blockquote>", "</blockquote>" }),
    .def(Node.L0Kind.bold_quote_block, .{ "<blockquote><strong>", "</strong></blockquote>" }),
    .def(Node.L0Kind.italic_quote_block, .{ "<blockquote><em>", "</em></blockquote>" }),
    .def(Node.L0Kind.bold_italic_quote_block, .{ "<blockquote><em><strong>", "</strong></em></blockquote>" }),

    .def(Node.L0Kind.paragraph, .{ "<p>", "</p>" }),
    .def(Node.L0Kind.nonparagraph, .{ "", "" }),

    .def(Node.L0Kind.code_block_header, .{ "<div class=\"code-header\">", "</div>" }),
    .def(Node.L0Kind.code_block_meta, .{ "<pre><code class=\"language-", "\">" }),
    .def(Node.L0Kind.code_block, .{ "", "</code></pre>" }),

    .def(Node.L0Kind.unordered_list_begin, "<ul>"),
    .def(Node.L0Kind.unordered_list_end, "</ul>"),

    .def(Node.L0Kind.dash_item, .{ "<li>", "</li>" }),

    .def(Node.L0Kind.ordered_list_begin, "<ol>"),
    .def(Node.L0Kind.ordered_list_end, "</ol>"),

    .def(Node.L0Kind.num_dot_item_label, .{ "<li value=\"", "\">" }),
    .def(Node.L0Kind.num_dot_item_text, .{ "", "</li>" }),

    .def(Node.L0Kind.num_paren_item_label, .{ "<li value=\"", "\">" }),
    .def(Node.L0Kind.num_paren_item_text, .{ "", "</li>" }),

    .def(Node.L1Kind.inline_code, .{ "<code>", "</code>" }),

    .def(Node.L1Kind.bold, .{ "<strong>", "</strong>" }),
    .def(Node.L1Kind.italic, .{ "<em>", "</em>" }),
    .def(Node.L1Kind.bold_italic, .{ "<strong><em>", "</em></strong>" }),

    .def(Node.L1Kind.strikethrough, .{ "<del>", "</del>" }),
    .def(Node.L1Kind.strikethrough_bold, .{ "<del><strong>", "</strong></del>" }),
    .def(Node.L1Kind.strikethrough_italic, .{ "<del><em>", "</em></del>" }),
    .def(Node.L1Kind.strikethrough_bold_italic, .{ "<del><strong><em>", "</em></strong></del>" }),

    .def(Node.L1Kind.link, &command_link),
    .def(Node.L1Kind.img, &command_img),
    .def(Node.L1Kind.raw, .{ "", "" }), // just passed through
    .def(Node.L1Kind.script, .{ "<script src=\"", "\"></script>" }),
};

fn command_link(g: *Generator, span: @Vector(2, usize)) Generator.GenError!void {
    for (g.textin[span[0]..span[1]], 0..) |c, i| {
        if (c == ',') {
            g.print("<a href='");
            g.print_span(span[0], span[0] + i);
            g.print("'>");
            g.print_span(span[0] + i + 1, span[1]);
            g.print("</a>");
            return;
        }
    }

    g.print("<a href='");
    g.print_span(span[0], span[1]);
    g.print("'>");
    g.print_span(span[0], span[1]);
    g.print("</a>");
}

fn command_img(g: *Generator, span: @Vector(2, usize)) Generator.GenError!void {
    for (g.textin[span[0]..span[1]], 0..) |c, i| {
        if (c == ',') {
            g.print("<figure><img src='");
            g.print_span(span[0], span[0] + i);
            g.print("' alt='");
            g.print_span(span[0] + i + 1, span[1]);
            g.print("'><figcaption>");
            g.print_span(span[0] + i + 1, span[1]);
            g.print("</figcaption></figure>");
            return;
        }
    }

    g.print("<img src='");
    g.print_span(span[0], span[1]);
    g.print("' alt='");
    g.print_span(span[0], span[1]);
    g.print("'></figure>");
}
