const std = @import("std");
const Generator = @import("Generator.zig");
const Node = @import("../element/Node.zig");
const Rule = @import("../element/Rule.zig");
const hack = @import("../hack.zig");
const crash = @import("../ErrorReporter.zig").crash;

pub const datatable = hack.StructByteMap(.{
    .{ &.{Node.L0Kind.begin}, Rule.GenDef.def("<!DOCTYPE html><html>") },
    .{ &.{Node.L0Kind.end}, Rule.GenDef.def("</body></html>\n\n <!-- generated by ct2html -->\n") },
    .{ &.{Node.L0Kind.head_anchor}, Rule.GenDef.def(&head_sec) },
    .{ &.{Node.L0Kind.heading1}, Rule.GenDef.def(&anchored_heading1) },
    .{ &.{Node.L0Kind.heading2}, Rule.GenDef.def(&anchored_heading2) },
    .{ &.{Node.L0Kind.heading3}, Rule.GenDef.def(&anchored_heading3) },
    .{ &.{Node.L0Kind.heading4}, Rule.GenDef.def(&anchored_heading4) },
    .{ &.{Node.L0Kind.heading5}, Rule.GenDef.def(&anchored_heading5) },
    .{ &.{Node.L0Kind.heading6}, Rule.GenDef.def(&anchored_heading6) },

    .{ &.{Node.L0Kind.quote_block}, Rule.GenDef.def(.{ "<blockquote>", "</blockquote>" }) },
    .{ &.{Node.L0Kind.bold_quote_block}, Rule.GenDef.def(.{ "<blockquote><strong>", "</strong></blockquote>" }) },
    .{ &.{Node.L0Kind.italic_quote_block}, Rule.GenDef.def(.{ "<blockquote><em>", "</em></blockquote>" }) },
    .{ &.{Node.L0Kind.bold_italic_quote_block}, Rule.GenDef.def(.{ "<blockquote><em><strong>", "</strong></em></blockquote>" }) },

    .{ &.{Node.L0Kind.paragraph}, Rule.GenDef.def(.{ "<p>", "</p>" }) },
    .{ &.{Node.L0Kind.nonparagraph}, Rule.GenDef.def(.{ "", "" }) },

    .{ &.{Node.L0Kind.code_block_header}, Rule.GenDef.def(.{ "<div class=\"code-header\">", "</div>" }) },
    .{ &.{Node.L0Kind.code_block_meta}, Rule.GenDef.def(.{ "<pre><code class=\"language-", "\">" }) },
    .{ &.{Node.L0Kind.code_block}, Rule.GenDef.def(.{ "", "</code></pre>" }) },

    .{ &.{Node.L0Kind.unordered_list_begin}, Rule.GenDef.def("<ul>") },
    .{ &.{Node.L0Kind.unordered_list_end}, Rule.GenDef.def("</ul>") },

    .{ &.{Node.L0Kind.dash_item}, Rule.GenDef.def(.{ "<li>", "</li>" }) },

    .{ &.{Node.L0Kind.ordered_list_begin}, Rule.GenDef.def("<ol>") },
    .{ &.{Node.L0Kind.ordered_list_end}, Rule.GenDef.def("</ol>") },

    .{ &.{Node.L0Kind.num_dot_item_label}, Rule.GenDef.def(.{ "<li value=\"", "\">" }) },
    .{ &.{Node.L0Kind.num_dot_item_text}, Rule.GenDef.def(.{ "", "</li>" }) },

    .{ &.{Node.L0Kind.num_paren_item_label}, Rule.GenDef.def(.{ "<li value=\"", "\">" }) },
    .{ &.{Node.L0Kind.num_paren_item_text}, Rule.GenDef.def(.{ "", "</li>" }) },

    .{ &.{Node.L0Kind.img}, Rule.GenDef.def(&command_img) },
    .{ &.{Node.L0Kind.script}, Rule.GenDef.def(.{ "<script src=\"", "\"></script>" }) },
    .{ &.{Node.L0Kind.ar}, Rule.GenDef.def(.{ "<p dir=\"rtl\" lang=\"ar\">", "</p>" }) },
    .{ &.{Node.L0Kind.header}, Rule.GenDef.def(.{ "<header>", "</header>" }) },
    .{ &.{Node.L0Kind.footer}, Rule.GenDef.def(.{ "<footer>", "</footer>" }) },
    // L1
    .{ &.{Node.L1Kind.inline_code}, Rule.GenDef.def(.{ "<code>", "</code>" }) },

    .{ &.{Node.L1Kind.bold}, Rule.GenDef.def(.{ "<strong>", "</strong>" }) },
    .{ &.{Node.L1Kind.italic}, Rule.GenDef.def(.{ "<em>", "</em>" }) },
    .{ &.{Node.L1Kind.bold_italic}, Rule.GenDef.def(.{ "<strong><em>", "</em></strong>" }) },

    .{ &.{Node.L1Kind.strikethrough}, Rule.GenDef.def(.{ "<del>", "</del>" }) },
    .{ &.{Node.L1Kind.strikethrough_bold}, Rule.GenDef.def(.{ "<del><strong>", "</strong></del>" }) },
    .{ &.{Node.L1Kind.strikethrough_italic}, Rule.GenDef.def(.{ "<del><em>", "</em></del>" }) },
    .{ &.{Node.L1Kind.strikethrough_bold_italic}, Rule.GenDef.def(.{ "<del><strong><em>", "</em></strong></del>" }) },

    .{ &.{Node.L1Kind.link}, Rule.GenDef.def(&command_link) },
    .{ &.{Node.L1Kind.raw}, Rule.GenDef.def(.{ "", "" }) }, // just passed through
    .{ &.{Node.L1Kind.ar}, Rule.GenDef.def(.{ "<span dir=\"rtl\" lang=\"ar\">", "</span>" }) },
    .{ &.{Node.L1Kind.div}, Rule.GenDef.def(&command_div) },
    .{ &.{Node.L1Kind.span}, Rule.GenDef.def(&command_span) },
    .{ &.{Node.L1Kind.color}, Rule.GenDef.def(&command_color) },
    .{ &.{Node.L1Kind.fs}, Rule.GenDef.def(&command_fs) },
}).init();

// for those attributes that get generated into the head section
fn head_sec(g: *Generator, _: ?@Vector(2, usize)) Generator.GenError!void {
    g.print("<head>");

    while (g.attributor.pop()) |l0node| {
        switch (l0node.kind) {
            .style => {
                g.print("<link rel=\"stylesheet\" href=\"");
                g.print_span(l0node.span.?[0], l0node.span.?[1]);
                g.print("\">");
            },
            .script => {
                g.print("<script src=\"");
                g.print_span(l0node.span.?[0], l0node.span.?[1]);
                g.print("\"></script>");
            },
            .title => {
                g.print("<title>");
                g.print_span(l0node.span.?[0], l0node.span.?[1]);
                g.print("</title>");
            },
            else => {},
        }
    }
    g.attributor.reset_cursor();
    g.print("</head>\n<body>");
}

inline fn generic_anchored_heading(
    g: *Generator,
    span: ?@Vector(2, usize),
    headingnodekind: Node.L0Kind,
) Generator.GenError!void {
    if (span == null) crash(error.NullSpan);

    const anchorbuf: []u8 = g.alloc.alloc(u8, span.?[1] - span.?[0]) catch crash(error.OOM);
    defer g.alloc.free(anchorbuf);
    @memcpy(anchorbuf, g.textin[span.?[0]..span.?[1]]);

    for (anchorbuf) |*c| {
        if (!std.ascii.isAlphanumeric(c.*)) {
            c.* = '-';
        } else if (std.ascii.isUpper(c.*)) {
            c.* = std.ascii.toLower(c.*);
        }
    }

    switch (headingnodekind) {
        .heading1 => g.print("<h1>"),
        .heading2 => g.print("<h2 "),
        .heading3 => g.print("<h3 "),
        .heading4 => g.print("<h4 "),
        .heading5 => g.print("<h5 "),
        .heading6 => g.print("<h6 "),
        else => @compileError("Not a heading node"),
    }

    defer switch (headingnodekind) {
        .heading1 => g.print("</h1>"),
        .heading2 => g.print("</h2>"),
        .heading3 => g.print("</h3>"),
        .heading4 => g.print("</h4>"),
        .heading5 => g.print("</h5>"),
        .heading6 => g.print("</h6>"),
        else => @compileError("Not a heading node"),
    };

    if (headingnodekind == .heading1) {
        g.print_span(span.?[0], span.?[1]);
        return;
    }

    g.print("id=\"");
    g.print(anchorbuf);
    g.print("\"><a href=\"#");
    g.print(anchorbuf);
    g.print("\" class=\"heading-link\">");
    if (g.attributor.get_newest(.heading_icon)) |l0_icon_node| {
        g.print("<span class=\"chain-icon\">");
        g.print_span(l0_icon_node.span.?[0], l0_icon_node.span.?[1]);
        g.print("</span>");
    }

    g.print_span(span.?[0], span.?[1]);
    g.print("</a>");
    // heading closing tag defered
}

fn anchored_heading1(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    return generic_anchored_heading(g, span, .heading1);
}
fn anchored_heading2(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    return generic_anchored_heading(g, span, .heading2);
}
fn anchored_heading3(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    return generic_anchored_heading(g, span, .heading3);
}
fn anchored_heading4(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    return generic_anchored_heading(g, span, .heading4);
}
fn anchored_heading5(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    return generic_anchored_heading(g, span, .heading5);
}
fn anchored_heading6(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    return generic_anchored_heading(g, span, .heading6);
}

fn command_link(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    if (span == null) crash(error.NullSpan);

    for (g.textin[span.?[0]..span.?[1]], 0..) |c, i| {
        if (c == ',') {
            g.print("<a href='");
            g.print_span(span.?[0], span.?[0] + i);
            g.print("'>");
            g.print_span(span.?[0] + i + 1, span.?[1]);
            g.print("</a>");
            return;
        }
    }

    g.print("<a href='");
    g.print_span(span.?[0], span.?[1]);
    g.print("'>");
    g.print_span(span.?[0], span.?[1]);
    g.print("</a>");
}

fn command_img(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    if (span == null) crash(error.NullSpan);

    for (g.textin[span.?[0]..span.?[1]], 0..) |c, i| {
        if (c == ',') {
            g.print("<figure><img src='");
            g.print_span(span.?[0], span.?[0] + i);
            g.print("' alt='");
            g.print_span(span.?[0] + i + 1, span.?[1]);
            g.print("'><figcaption>");
            g.print_span(span.?[0] + i + 1, span.?[1]);
            g.print("</figcaption></figure>");
            return;
        }
    }

    g.print("<img src='");
    g.print_span(span.?[0], span.?[1]);
    g.print("' alt='");
    g.print_span(span.?[0], span.?[1]);
    g.print("'></figure>");
}

fn command_div(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    if (span == null) crash(error.NullSpan);

    g.print("<div");

    for (g.textin[span.?[0]..span.?[1]], 0..) |c, i| {
        if (c == ',') { // class string
            g.print(" class=\"");
            g.print_span(span.?[0], span.?[0] + i);
            g.print("\">");
            g.print_span(span.?[0] + i + 1, span.?[1]);
            g.print("</div>");
            return;
        }
    }
    g.print(">");
    g.print_span(span.?[0], span.?[1]);
    g.print("</div>");
}

fn command_span(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    if (span == null) crash(error.NullSpan);

    g.print("<span");

    for (g.textin[span.?[0]..span.?[1]], 0..) |c, i| {
        if (c == ',') { // class string
            g.print(" class=\"");
            g.print_span(span.?[0], span.?[0] + i);
            g.print("\">");
            g.print_span(span.?[0] + i + 1, span.?[1]);
            g.print("</span>");
            return;
        }
    }
    g.print(">");
    g.print_span(span.?[0], span.?[1]);
    g.print("</span>");
}

fn command_color(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    if (span == null) crash(error.NullSpan);

    for (g.textin[span.?[0]..span.?[1]], 0..) |c, i| {
        if (c == ',') { // color
            g.print("<span style=\"color: ");
            g.print_span(span.?[0], span.?[0] + i);
            g.print(";\">");
            g.print_span(span.?[0] + i + 1, span.?[1]);
            g.print("</span>");
            return;
        }
    }

    return g.e.file_report(Generator.GenError.InvalidL1Format, false, "Not of format: (<color>, <text>)", null);
}

fn command_fs(g: *Generator, span: ?@Vector(2, usize)) Generator.GenError!void {
    if (span == null) crash(error.NullSpan);

    for (g.textin[span.?[0]..span.?[1]], 0..) |c, i| {
        if (c == ',') { // font size
            g.print("<span style=\"font-size: ");
            g.print_span(span.?[0], span.?[0] + i);
            g.print(";\">");
            g.print_span(span.?[0] + i + 1, span.?[1]);
            g.print("</span>");
            return;
        }
    }

    return g.e.file_report(Generator.GenError.InvalidL1Format, false, "Not of format: (<font-size>, <text>)", null);
}
