const std = @import("std");
const Generator = @import("Generator.zig");
const Node = @import("../element/Node.zig");
const Rule = @import("../element/Rule.zig");
const hack = @import("../hack.zig");
const crash = @import("../ErrorReporter.zig").crash;

pub const datatable = hack.StructByteMap(.{
    .{
        .{Node.L0Kind.begin},
        Rule.GenDef.def("<!DOCTYPE html><html><head><meta charset=\"UTF-8\">", "", true),
    },
    .{
        .{Node.L0Kind.end},
        Rule.GenDef.def("</body></html>\n\n <!-- generated by ct2html -->\n", "", true),
    },
    .{
        .{Node.L0Kind.head_anchor},
        Rule.GenDef.def(&head_sec, "", true),
    },
    .{
        .{Node.L0Kind.heading1},
        Rule.GenDef.def("<h1>", "</h1>", false),
    },
    .{
        .{Node.L0Kind.heading2},
        Rule.GenDef.def(&generic_pre_anchored_heading, "</a></h2>", false),
    },
    .{
        .{Node.L0Kind.heading3},
        Rule.GenDef.def(&generic_pre_anchored_heading, "</a></h3>", false),
    },
    .{
        .{Node.L0Kind.heading4},
        Rule.GenDef.def(&generic_pre_anchored_heading, "</a></h4>", false),
    },
    .{
        .{Node.L0Kind.heading5},
        Rule.GenDef.def(&generic_pre_anchored_heading, "</a></h5>", false),
    },
    .{
        .{Node.L0Kind.heading6},
        Rule.GenDef.def(&generic_pre_anchored_heading, "</a></h6>", false),
    },

    .{
        .{Node.L0Kind.quote_block},
        Rule.GenDef.def("<blockquote>", "</blockquote>", false),
    },
    .{
        .{Node.L0Kind.bold_quote_block},
        Rule.GenDef.def("<blockquote><strong>", "</strong></blockquote>", false),
    },
    .{
        .{Node.L0Kind.italic_quote_block},
        Rule.GenDef.def("<blockquote><em>", "</em></blockquote>", false),
    },
    .{
        .{Node.L0Kind.bold_italic_quote_block},
        Rule.GenDef.def("<blockquote><em><strong>", "</strong></em></blockquote>", false),
    },

    .{
        .{Node.L0Kind.paragraph},
        Rule.GenDef.def("<p>", "</p>", false),
    },
    .{
        .{Node.L0Kind.nonparagraph},
        Rule.GenDef.def("", "", false),
    },

    .{
        .{Node.L0Kind.code_block_header},
        Rule.GenDef.def("<div class=\"code-header\">", "</div>", false),
    },
    .{
        .{Node.L0Kind.code_block_meta},
        Rule.GenDef.def("<pre><code class=\"language-", "\">", false),
    },
    .{
        .{Node.L0Kind.code_block},
        Rule.GenDef.def("", "</code></pre>", true),
    },

    .{
        .{Node.L0Kind.unordered_list_begin},
        Rule.GenDef.def("<ul>", "", false),
    },
    .{
        .{Node.L0Kind.unordered_list_end},
        Rule.GenDef.def("</ul>", "", false),
    },

    .{
        .{Node.L0Kind.dash_item},
        Rule.GenDef.def("<li>", "</li>", false),
    },

    .{
        .{Node.L0Kind.ordered_list_begin},
        Rule.GenDef.def("<ol>", "", false),
    },
    .{
        .{Node.L0Kind.ordered_list_end},
        Rule.GenDef.def("</ol>", "", false),
    },

    .{
        .{Node.L0Kind.num_dot_item_label},
        Rule.GenDef.def("<li value=\"", "\">", false),
    },
    .{
        .{Node.L0Kind.num_dot_item_text},
        Rule.GenDef.def("", "</li>", false),
    },

    .{
        .{Node.L0Kind.num_paren_item_label},
        Rule.GenDef.def("<li value=\"", "\">", false),
    },
    .{
        .{Node.L0Kind.num_paren_item_text},
        Rule.GenDef.def("", "</li>", false),
    },

    .{
        .{Node.L0Kind.blk_cmd_img_0src},
        Rule.GenDef.def("<figure><img src=\"", "\" ", false),
    },
    .{
        .{Node.L0Kind.blk_cmd_img_1size},
        Rule.GenDef.def("style=\"width:", "; height: auto;\" alt=\"\" />", false),
    },
    .{
        .{Node.L0Kind.blk_cmd_img_2caption},
        Rule.GenDef.def("<figcaption>", "</figcaption></figure>", false),
    },

    .{
        .{Node.L0Kind.blk_cmd_script_link},
        Rule.GenDef.def("<script src=\"", "\"></script>", false),
    },
    .{
        .{Node.L0Kind.blk_cmd_style_link},
        Rule.GenDef.def("<link rel=\"stylesheet\" href=\"", "\">", false),
    },
    .{
        .{Node.L0Kind.blk_cmd_ar_text},
        Rule.GenDef.def("<p dir=\"rtl\" lang=\"ar\">", "</p>", false),
    },
    .{
        .{Node.L0Kind.blk_cmd_header_text},
        Rule.GenDef.def("<header>", "</header>", false),
    },
    .{
        .{Node.L0Kind.blk_cmd_footer_text},
        Rule.GenDef.def("<footer>", "</footer>", false),
    },

    // L1
    .{
        .{Node.L1Kind.inline_code},
        Rule.GenDef.def("<code>", "</code>", true),
    },

    .{
        .{Node.L1Kind.bold},
        Rule.GenDef.def("<strong>", "</strong>", false),
    },
    .{
        .{Node.L1Kind.italic},
        Rule.GenDef.def("<em>", "</em>", false),
    },
    .{
        .{Node.L1Kind.bold_italic},
        Rule.GenDef.def("<strong><em>", "</em></strong>", false),
    },

    .{
        .{Node.L1Kind.strikethrough},
        Rule.GenDef.def("<del>", "</del>", false),
    },
    .{
        .{Node.L1Kind.strikethrough_bold},
        Rule.GenDef.def("<del><strong>", "</strong></del>", false),
    },
    .{
        .{Node.L1Kind.strikethrough_italic},
        Rule.GenDef.def("<del><em>", "</em></del>", false),
    },
    .{
        .{Node.L1Kind.strikethrough_bold_italic},
        Rule.GenDef.def("<del><strong><em>", "</em></strong></del>", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_raw_text},
        Rule.GenDef.def("", "", true),
    },
    .{
        .{Node.L1Kind.inl_cmd_link_0url},
        Rule.GenDef.def("<a href=\"", "\">", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_link_1displayname},
        Rule.GenDef.def("", "</a>", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_ar_text},
        Rule.GenDef.def("<span dir=\"rtl\" lang=\"ar\">", "</span>", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_div_0class},
        Rule.GenDef.def("<div class=\"", "\">", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_div_1text},
        Rule.GenDef.def("", "</div>", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_span_0class},
        Rule.GenDef.def("<span class=\"", "\">", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_span_1text},
        Rule.GenDef.def("", "</span>", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_color_0color},
        Rule.GenDef.def("<span style=\"color: ", "\">", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_color_1text},
        Rule.GenDef.def("", "</span>", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_fs_0size},
        Rule.GenDef.def("<span style=\"font-size: ", "\">", false),
    },
    .{
        .{Node.L1Kind.inl_cmd_fs_1text},
        Rule.GenDef.def("", "</span>", false),
    },
}).init();

// for those attributes that get generated into the head section
fn head_sec(g: *Generator, _: *anyopaque) Generator.GenError!?@Vector(2, usize) {
    while (g.attributor.pop()) |l0node| {
        switch (l0node.kind) {
            .style => {
                g.print("<link rel=\"stylesheet\" href=\"");
                g.print_span(l0node.span.?[0], l0node.span.?[1]);
                g.print("\">");
            },
            .script => {
                g.print("<script src=\"");
                g.print_span(l0node.span.?[0], l0node.span.?[1]);
                g.print("\"></script>");
            },
            .title => {
                g.print("<title>");
                g.print_span(l0node.span.?[0], l0node.span.?[1]);
                g.print("</title>");
            },
            else => {},
        }
    }
    g.attributor.reset_cursor();
    g.print("</head>\n<body>"); // opening was already printed.
    return null; // nothing to inspect in here
}

fn generic_pre_anchored_heading(
    g: *Generator,
    node: *anyopaque,
) Generator.GenError!?@Vector(2, usize) {
    const realnode: *Node.L0 = @ptrCast(@alignCast(node));
    const span = realnode.span;

    if (span == null) crash(error.NullSpan);

    const anchorbuf: []u8 = g.alloc.alloc(u8, span.?[1] - span.?[0]) catch crash(error.OOM);
    defer g.alloc.free(anchorbuf);
    @memcpy(anchorbuf, g.textin[span.?[0]..span.?[1]]);

    for (anchorbuf) |*c| {
        if (!std.ascii.isAlphanumeric(c.*)) {
            c.* = '-';
        } else if (std.ascii.isUpper(c.*)) {
            c.* = std.ascii.toLower(c.*);
        }
    }

    switch (realnode.kind) {
        .heading2 => g.print("<h2 "),
        .heading3 => g.print("<h3 "),
        .heading4 => g.print("<h4 "),
        .heading5 => g.print("<h5 "),
        .heading6 => g.print("<h6 "),
        else => unreachable,
    }

    g.print("id=\"");
    g.print(anchorbuf);
    g.print("\"><a href=\"#");
    g.print(anchorbuf);
    g.print("\" class=\"heading-link\">");
    if (g.attributor.get_newest(.heading_icon)) |l0_icon_node| {
        g.print("<span class=\"chain-icon\">");
        g.print_span(l0_icon_node.span.?[0], l0_icon_node.span.?[1]);
        g.print("</span>");
    }

    return span;
}

fn pre_command_img(g: *Generator, node: *anyopaque) Generator.GenError!?@Vector(2, usize) {
    const realnode: *Node.L0 = @ptrCast(@alignCast(node));
    const span = realnode.span;

    if (span == null) crash(error.NullSpan);

    var commas: [2]usize = .{ 0, 0 };
    var postcomma_argstarts: [2]usize = .{ 0, 0 };
    var commac: usize = 0;
    var last_c: usize = 0;
    for (g.textin[span.?[0]..span.?[1]], 0..) |c, i| {
        if (c == ',') {
            if (last_c == '\\') continue;

            for (g.textin[span.?[0] + i + 1 .. span.?[1]], i + 1..) |c2, j| {
                if (c2 != ' ' and c2 != '\t') {
                    postcomma_argstarts[commac] = j;
                    break;
                }
            }

            commas[commac] = i;
            commac += 1;
            if (commac >= 2) break;
        }
        last_c = c;
    }

    if (commac == 0) {
        g.print("<img src=\"");
        g.print_span(span.?[0], span.?[1]);
        g.print("\" alt=\"");
        g.print_span(span.?[0], span.?[1]);
        g.print("\"></figure>");
        return null; // just the link
    }

    if (commac == 1) {
        g.print("<figure><img src=\"");
        g.print_span(span.?[0], span.?[0] + commas[0]);
        g.print("\" alt=\"");
        return @Vector(2, usize){ span.?[0] + postcomma_argstarts[0], span.?[1] };
    }

    if (commac == 2) {
        g.print("<figure><img src=\"");
        g.print_span(span.?[0], span.?[0] + commas[0]);
        g.print("\" style=\"width:");
        g.print_span(span.?[0] + postcomma_argstarts[0], span.?[0] + commas[1]);
        g.print("; height: auto;\" alt=\"");
        g.print_span(span.?[0] + postcomma_argstarts[1], span.?[1]);
        g.print("\"><figcaption>");
        return @Vector(2, usize){ span.?[0] + postcomma_argstarts[1], span.?[1] };
    }

    unreachable;
}

fn post_command_img(g: *Generator, node: *anyopaque) Generator.GenError!void {
    const realnode: *Node.L0 = @ptrCast(@alignCast(node));
    const span = realnode.span;

    if (span == null) crash(error.NullSpan);

    var commas: [2]usize = .{ 0, 0 };
    var postcomma_argstarts: [2]usize = .{ 0, 0 };
    var commac: usize = 0;
    var last_c: usize = 0;
    for (g.textin[span.?[0]..span.?[1]], 0..) |c, i| {
        if (c == ',') {
            if (last_c == '\\') continue;

            for (g.textin[span.?[0] + i + 1 .. span.?[1]], i + 1..) |c2, j| {
                if (c2 != ' ' and c2 != '\t') {
                    postcomma_argstarts[commac] = j;
                    break;
                }
            }

            commas[commac] = i;
            commac += 1;
            if (commac >= 2) break;
        }
        last_c = c;
    }

    if (commac == 1 or commac == 2) {
        g.print("</figcaption></figure>");
    } // else nothing, since we already printed it.
}
