# you need to set:
# - <YOUR_DOMAIN> to your domain name, or another folder where you want to serve the page
# - <PATH_TO_REPO> to the path of the ct2html repo on your

server {
	listen 80 default_server;       # or another server name
	listen [::]:80 default_server;  # or another server name

	root /var/www/<YOUR_DOMAIN>;
	index main.ct; 

	server_name localhost 127.0.0.1 ::1;

	location / {
        try_files $uri $uri/ /index.ct;
	}

	location ~ \.ct$ {
        gzip off;
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        include fastcgi_params;
	   	fastcgi_param SCRIPT_FILENAME <PATH_TO_REPO>/ct2html/nginx-helpers/ct2html-cgi;
		fastcgi_param CT_FILE $document_root$uri;
	}
}